// components/DisclaimerFooter.js
import React from 'react';

const DisclaimerFooter = () => {
    return (
        <div className="bg-[#1a2033] py-16 text-[#777] px-4">
            <div className="Container-Div mx-auto max-w-6xl">
                {/* Main Disclaimer Text */}
                <p className="mb-6">
                    CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. 61% of retail investor accounts lose money when trading CFDs with this provider. You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.
                </p>

                {/* Regulatory Information */}
                <p className="mb-6">
                    <span className="  ">eToro (Europe) Ltd.</span>, a Financial Services Company authorised and regulated by the Cyprus Securities Exchange Commission (CySEC) under the license # 109/10. <br />
                    <span className="  ">eToro (UK) Ltd</span>, a Financial Services Company authorised and regulated by the Financial Conduct Authority (FCA) under the license FRN 583263. <br />
                    <span className="  ">eToro AUS Capital Limited</span> is authorised by the Australian Securities and Investments Commission (ASIC) to provide financial services under Australian Financial Services License 491139 <br />
                    <span className="  ">eToro (Seychelles) Ltd.</span> is licenced by the Financial Services Authority Seychelles (“FSAS”) to provide broker-dealer services under the Securities Act 2007 License #SD076
                </p>

                {/* Israeli Regulation */}
                <p className="mb-6">
                    eToro applied to the Israeli Securities Authority for a permit under section 49A of the Securities Law to offer Stocks to clients who reside in Israel, and it is offering stocks in Israel by virtue of the transitional provision, which allows those who operated in Israel and applied for a permit to continue operating until a decision is made on the application. To the extent that the Authority’s permit is granted in the future under section 49A of the Securities Law, the activities of the permit holder will not be supervised by the Israeli Securities Authority. The permit will not express an opinion on the nature of the service provided by the permit holder or on the risks involved. eToro is not supervised by the Israeli Securities Authority and does not have a trading platform license and/or portfolio management license in Israel.
                </p>

                {/* Risk Disclosures */}
                <p className="mb-6">
                    <span className="">Past performance is not an indication of future results</span> <br />
                    <a href="#" className="   hover:underline">General Risk Disclosure</a> | <a href="#" className="   hover:underline">Terms & Conditions</a>
                </p>

                <p className="mb-6">
                    You should seek advice from an independent and suitably licensed financial advisor and ensure that you have the risk appetite, relevant experience and knowledge before you decide to trade. Under no circumstances shall eToro have any liability to any person or entity for (a) any loss or damage in whole or part caused by, resulting from, or relating to any transactions related to CFDs or (b) any direct, indirect, special, consequential or incidental damages whatsoever.
                </p>

                <p className="mb-6">
                    Cryptocurrencies markets are unregulated services which are not governed by any specific European regulatory framework (including MiFID). Therefore when using our Cryptocurrencies Trading Service you will not benefit from the protections available to clients receiving MiFID regulated investment services, such as access to the Cyprus Investor Compensation Fund (ICF)/the Financial Services Compensation Scheme (FSCS) and the Financial Ombudsman Service for dispute resolution.
                </p>

                <p className="mb-6">
                    Trading with eToro by following and/or copying or replicating the trades of other traders involves a high level of risks, even when following and/or copying or replicating the top-performing traders. Such risks includes the risk that you may be following/copying the trading decisions of possibly inexperienced/unprofessional traders, or traders whose ultimate purpose or intention, or financial status may differ from yours. Past performance of an eToro Community Member is not a reliable indicator of his future performance. Content on eToro’s social trading platform is generated by members of its community and does not contain advice or recommendations by or on behalf of eToro – Your Social Investment Network.
                </p>

                {/* Copyright */}
                <p className="mb-6   ">
                    Copyright © 2006-2022 eToro – Your Social Investment Network, All rights reserved.
                </p>

                {/* eToro Money */}
                <p className="mb-6">
                    eToro Money related services and accounts are provided by <span className="  ">eToro Money UK Limited</span> (company registration number 07712717), with registered address Maclaren 3B, The Lancastrian Office Centre, Talbot Road, Manchester, M32 0FP. eToro Money UK Ltd is authorised by the Financial Conduct Authority (FCA) under the Electronic Money Regulations 2011 (FRN 900203) for the issuing of electronic money. Terms apply, etoroprod.wpengine.com/money
                </p>

                <p className="mb-6">
                    eToro Money related services and accounts are provided by <span className="  ">eToro Money Malta Limited</span> (company registration number C97952), with registered address 52, St. Christopher Street, Valletta VLT 1462. eToro Money Malta Ltd is regulated by the Malta Financial Services Authority and licensed to operate as a Financial Institution under the 2nd and 3rd Schedule of the Financial Institutions Act (Ch. 376 of the Laws of Malta).
                </p>

                <p>
                    Funds held in your eToro Money account are not protected by the banking depository compensation scheme. Your funds are held in a designated safeguarding account at an authorised credit institution in the UK or EU. Unlike banks, these safeguarded funds cannot be used by eToro Money for anything other than for facilitating your payment transactions. This means that your funds held by eToro Money are protected at all times and in the unlikely event of insolvency, your losses are limited to the cost of repatriation of funds only.
                </p>
            </div>
        </div>
    );
};

export default DisclaimerFooter;